### ISSUE TITLE
Enhancements to job log viewer

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/vscode-ibmi-projectexplorer#190]
The new Job Log tree should have the structure

```
job date
   object <- source
      command
      message1
      ...
      messageN
job date 2
...
```
- [x] Replace command level tree item with `<object>` as the label and `<source>` as the description
- [x] The above should be colored red if the command failed (or at least the icon for it will be a red x or green check)
- [x] Add the command at the same level of the messages
- [x] Add action to toggle failures
- [ ] Add action to filter in order to view above a severity level
- [ ] Add action to view output for individual objects

**Comment by SanjulaGanepola** [comment]
There should also be an action to view the output for individual objects
