### ISSUE TITLE
update of member text fails

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/vscode-ibmi-projectexplorer#209]
Attempt to specify member text on <p8adt05>PAYROLLORG/QRPGLESRC(ERRORTABLE) in Library List heading of Project Explorer
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/7b6500f0-e8f9-413b-b79e-db0c91532dad)

The command fails

<img width="477" alt="image" src="https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/b6080f80-71a9-4554-becd-b865b566fab4">

![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/d4fc9d1b-a0a4-4cff-bf7c-099076ec0c85)

**Comment by SanjulaGanepola** [comment]
Looks like the right parameters were not being passed to the `updateMemberText` command in code4i. I can create a quick PR to fix this
