### ISSUE TITLE
Deleting an object from library in the Library List fails

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/vscode-ibmi-projectexplorer#223]
Error running command vscode-ibmi-projectexplorer.deleteObject: Cannot read properties of undefined (reading 'type'). This is likely caused by the extension that contributes vscode-ibmi-projectexplorer.deleteObject.

**Comment by edmundreinhardt** [comment]
@SanjulaGanepola any ideas

**Comment by sebjulliand** [comment]
@edmundreinhardt fixed that for you 😁

**Comment by edmundreinhardt** [comment]
Thank you!

**Comment by edmundreinhardt** [comment]
Delete object worked but other actions like change object description still do not
