### ISSUE TITLE
Changing library description on library in project explorer library list fails

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/vscode-ibmi-projectexplorer#227]
Attempt to do 
<img width="372" alt="image" src="https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/16c30a5d-37ae-4791-b06c-3f8398f64e85">
 and get result
<img width="479" alt="Screenshot 2023-09-28 at 9 20 39 AM" src="https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/7295cc09-9fdc-4ab5-b237-9d7f0995edc8">

all the actions on Objects work
But actions on libraries in the QSYS Browser fail as well

<img width="479" alt="Screenshot 2023-09-28 at 9 20 39 AM" src="https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/8a1335b4-672a-4597-9beb-000a19cd180b">

**Comment by sebjulliand** [comment]
RIght, I did Objects and Members but forgot the Libraries. I'll do that soon.

**Comment by edmundreinhardt** [comment]
Thank you
