### ISSUE TITLE
When assigning libraries to variables from QSYS browser, the value becomes QSYS/lowercaselibraryname should be UPPERCASELIBNAME

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/vscode-ibmi-projectexplorer#251]
<img width="271" alt="image" src="https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/9c36f51a-9f32-40f7-9639-66f14368bb47">
<img width="487" alt="image" src="https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/d4e35ec8-6a72-413c-825e-167e61f0d2c0">

**Comment by sebjulliand** [comment]
I'll fix that. The assignment to a variable keeps the case displayed in the browser. They are lowercase if this setting is enabled:
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11096890/0db07395-c441-4eb6-8e49-6013b8319481)

Disabling it will make uppercase the names.

**Comment by edmundreinhardt** [comment]
Thank you Seb

**Comment by sebjulliand** [comment]
> Thank you Seb

You're welcome 😉 Don't forget to merge the PR!
