### ISSUE TITLE
Need to set CURLIB and LIBL as environment variables based on iproj.json

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/vscode-ibmi-projectexplorer#254]
When commands are invoked in Code4i, these variables are used
This prevent the debugger from getting the right curlib when invoking the program to be compiled

**Comment by edmundreinhardt** [comment]
@SanjulaGanepola not sure if you have time to look at this?

**Comment by edmundreinhardt** [comment]
Needed for https://github.ibm.com/ibmi-toronto/cloudide4i/issues/2017

**Comment by SanjulaGanepola** [comment]
The `LIBLS` and `CURLIB` variables are default variables that get set by Code4i based on the user library list view that they have. In the case of i projects, the library list and current library that are set here do not affect these variables. The only case in which these default variables are overwritten is if the `curlib` field in the project's iproj.json is set to specifically `&CURLIB`. For `LIBLS` we don't have control over that as of right now as that would not be used anywhere directly in the iproj.json.

How should Project Explorer handle this or should Code4i handle this instead by setting these variables appropriately if there is an iproj.json and if not default to the current behaviour of using the user library list view?

**Comment by edmundreinhardt** [comment]
@worksofliam @SanjulaGanepola 
Liam does not want Code4i to do anything with iproj.json.  He considers that Project Explorer's responsibility.  Apparently LIBL is not such a high priority.  But for the program being debugged to be invoked with the right CURLIB, we should keep the CURLIB env variable in sync with our iproj.json curlib field.

@worksofliam it seems that there will still be a confiict at some level over what CURLIB should be and whether it derives its value from the Code 4 i library list, or the iproj.json one.
Does Code 4 i use the .env file to control CURLIB or some other mechanism?

**Comment by worksofliam** [comment]
> Does Code 4 i use the .env file to control CURLIB or some other mechanism?

Yes, an action is run against a Uri that is part of a workspace, Code for IBM i will pickup all the variables defined in `.env`. If you use `CURLIB` and `LIBL` in the `.env`, then it will override the connection wide one.

**Comment by edmundreinhardt** [comment]
The ugly thing is that we are now persisting duplicate values of CURLIB and LIBL.  1 copy  in iproj.json and another in .env. 
Both of these are exposed to the user and can get out of sync.
So if the user updates the .env file do we have to update iproj.json?  This is getting ugly.

**Comment by worksofliam** [comment]
@edmundreinhardt This was decided time ago when we also decided to stop creating default actions from the `buildCommand` and `compileCommand`. The reason we let Project Explorer handle this logic is because of the resolving it does for post and pre library list work.

The only variables Code for IBM i cares about is `LIBL` and `CURLIB` which are used for two things:

1. Compiling with CL commands (which you don't do through Project Explorer)
2. Debug settings (which is what this issue is open for)

**Comment by SanjulaGanepola** [comment]
Since Code4i does pick up variables from the `.env` file, whenever the users sets the `curlib` in their iproj.json file to `&CURLIB` then there will be no issue. I think the issue arises when the users uses some other variable name.
