### ISSUE TITLE
Library List not respected when compiling

### ISSUE THREAD

**Issue by rbeckham** [IBM/vscode-ibmi-projectexplorer#315]
I have an project setup using iproj.json. I am using BOB makei to build.  I'm slightly confused on how the library list feature works, and the documentation is not complete yet so I'm stuck.

I'm trying to compile one program but when I run compile its not respecting my library list.  Please see pictures for example.

Notice I am adding 2 libraries to preUsrLibl (OIPAYFILES, TKTLIB2) in that order.
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/6114419/aed86631-56e5-4690-ba88-773c7ba6368e)

When I run my compile though it flips the order and puts TKTLIB2 in front of OIPAYFILES which causes the compile to fail.
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/6114419/26ee81e4-d5f0-44a7-8065-7f545bd783e6)

and in my project explorer pane it looks correct?  Libraries are in the right order.
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/6114419/89370f34-ad8a-4839-b7ea-00db378f3d1e)

**Comment by edmundreinhardt** [comment]
THis is a valid issue, BOB should be traversing that list in reverse order if it is doing an addition to the beginnning of LIBL

**Comment by edmundreinhardt** [comment]
@irfanshar Irfan can you please fix this in BOB

**Comment by irfanshar** [comment]
> Fix incorrect link to library list and object library doc pages #316

This issue is addressed in https://github.com/IBM/ibmi-bob/pull/293

**Comment by edmundreinhardt** [comment]
@irfanshar Irfan, why don't you release Bob with this fix
