### ISSUE TITLE
Lib1 variable not showing 

### ISSUE THREAD

**Issue by jonnyz32** [IBM/vscode-ibmi-projectexplorer#317]
https://github.com/IBM/vscode-ibmi-projectexplorer/assets/42983653/161eaec5-e2b1-4f98-a183-00f245b120be

**Comment by jonnyz32** [comment]
From what I can see, it's only reading the variables from the iproj.json and not the .env. I.e if the var exists in the iproj.json it will show under variables, and if not it won't. The .env file is having no effect.

Uploading Screen Recording 2024-01-22 at 2.17.40 PM.mov…

**Comment by jonnyz32** [comment]
I suppose this is expected

**Comment by edmundreinhardt** [comment]
Yes Jonathan, the design is that any variable in the iproj.json will need to have a value supplied by the .env and the UI will prompt you to do that.
