### ISSUE TITLE
Adding empty string to preUsrLib or postUsrLibl results in @#$DEU being added to liblist

### ISSUE THREAD

**Issue by jonnyz32** [IBM/vscode-ibmi-projectexplorer#324]
https://github.com/IBM/vscode-ibmi-projectexplorer/assets/42983653/845b244b-0cdd-42b8-8911-8433b2982b09

**Comment by edmundreinhardt** [comment]
Very interesting.  Looks like it is finding the first alphabetic library

**Comment by edmundreinhardt** [comment]
@jonnyz32 can I assume this is Roma?

**Comment by edmundreinhardt** [comment]
Reproduced and fixed via commit f61549e3c50c38db4f8786473411911535dd8258
