### ISSUE TITLE
Compare source filter does not work

### ISSUE THREAD

**Issue by jonnyz32** [IBM/vscode-ibmi-projectexplorer#328]
When making changes in local workspace, the compare source filter does not show the changes. Possibly related to https://github.com/IBM/vscode-ibmi-projectexplorer/issues/326 
@edmundreinhardt @irfanshar

**Comment by edmundreinhardt** [comment]
I suspect it is, let's release and test again

**Comment by edmundreinhardt** [comment]
@william-xiang William, can you update Project Explorer to 2.6.2 so that Jonathan can test whether this issue is resolved

**Comment by edmundreinhardt** [comment]
@jonnyz32  Can you please test this

**Comment by jonnyz32** [comment]
Yep, this is working now. I'll close.
