### ISSUE TITLE
Adding "\"ABCDEFG\"" lib to library list results in issues

### ISSUE THREAD

**Issue by jonnyz32** [IBM/vscode-ibmi-projectexplorer#337]
When adding the library  "\\"abcdefg\\"" to the library list, it removes the library  "WDSCTEST" from liblist. As well \"abcdefg\", is the name of an existing library, so it should get added as well. A similar issue, is if you use just one quote, i.e "\"ABCDEFG", it will nuke the whole library list.

Uploading Screen Recording 2024-02-02 at 12.24.36 PM.mov…

**Comment by edmundreinhardt** [comment]
The movie is no uploaded, perhaps a box link will work. @jonnyz32

**Comment by jonnyz32** [comment]
Uploading Screen Recording 2024-02-02 at 12.24.36 PM.mov…

**Comment by jonnyz32** [comment]
https://github.com/IBM/vscode-ibmi-projectexplorer/assets/42983653/bd2d0062-4ba7-4bc2-a7a9-8973c3a444db

**Comment by jonnyz32** [comment]
This issue was found from QuotedMembersTest

**Comment by edmundreinhardt** [comment]
reproduced on Project Explorer 2.6.4

**Comment by edmundreinhardt** [comment]
It appears that the problem centers around 
https://vscode.dev/github/IBM/vscode-ibmi-projectexplorer/blob/main/node_modules/%40halcyontech/vscode-ibmi-types/api/IBMiContent.d.ts#L91
i.e. validateLibraryList() that does not accept quoted names

**Comment by edmundreinhardt** [comment]
<img width="1053" alt="image" src="https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/e4733b70-50a5-44c3-a337-cc3680b85869">

**Comment by edmundreinhardt** [comment]
Have slack in to Kevin Adler to confirm that this is known behaviour of liblist
