### ISSUE TITLE
Source filters don't show deleted files

### ISSUE THREAD

**Issue by jonnyz32** [IBM/vscode-ibmi-projectexplorer#345]
From the git view we can see the file vat.rpgleinc has been deleted, but when trying various source filters, we can not see the file vat.rpgleinc being listed as deleted. We had this functionality working in v1

https://github.com/IBM/vscode-ibmi-projectexplorer/assets/42983653/69a3604a-c9cd-480b-8d37-c45d13b23fcf

**Comment by jonnyz32** [comment]
I'm still having the issue where deleted file vat.rpgleinc not showing in filter "changes", "working changes", or "all". Having issues uploading screen recording now. Will try again later

**Comment by edmundreinhardt** [comment]
Yes, this is by design, the `deleted` files only show up in the `compare` filter, because that is the only one that looks at all of the remote files.

**Comment by jonnyz32** [comment]
@edmundreinhardt From the docs, it reads to me that all except the "Staged changes" filter should show it. I'm also having a hard time deciphering between "compare" and "changes". The definitions seem equivalent to me. ![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/42983653/570ec114-7028-45a8-a173-7aea6b540501)

**Comment by edmundreinhardt** [comment]
So the Compare compares all local files with all remote files, which is why it can detect files that have been deleted.
But the `Changes` only compares local files agains the *timestamp* of the last upload and has not idea about the contents of the remote IFS folder.
Working and Staged changes only look at git and not remote files
All simply copies all local files and does not look at remote files either

**Comment by jonnyz32** [comment]
I see. Well, maybe I'm interpreting it wrong, but "This method will upload all files which have been changed since the last upload", to me sounds like if I upload a.rpgle, and then later on I delete a.rpgle, I would expect that a.rpgle would be a file that has "changed since the last upload". Similarly, I would expect deploying with all, to make my local workspace to be in sync with my remote directory (including deleted files).

**Comment by edmundreinhardt** [comment]
Scenario for `changed` filter.  If a local file is  deleted that is not seen by the algorithm that compares timestamps and no change is deployed to the remote IFS.  I just tested that this is the way it works

Scenario for `all` filter:  All files will be uploaded, and none will be deleted

So the only scenario in which deleting a local file impacts the remote is using the `compare` filter

**Comment by edmundreinhardt** [comment]
Conclusion of our discussion with @jonnyz32 
 - drop the 2 git filters
Document what is going on with the other 3
Improve the All to remove all files in target dir before deploying 
Improve the Changes to track any deleted files  so they are also deleted  - these last 2 are subject to discussion with @worksofliam  and will be out of scope v2.0

**Comment by edmundreinhardt** [comment]
Documentation defect https://github.com/IBM/vscode-ibmi-projectexplorer/issues/408

**Comment by jonnyz32** [comment]
Another comment that I made that is also subject to discussion with Liam is the precense of a .deployignore file which would serve the unique purpose of excluding files to be deployed to the IBM i. This avoids the problem with the current implementation of using .gitignore for this purpose as there may be files that should be ignored by git, but not ignored in a deploy, or vice versa.
