### ISSUE TITLE
Renaming a library in the library list, doesn't add the renamed library to the list

### ISSUE THREAD

**Issue by jonnyz32** [IBM/vscode-ibmi-projectexplorer#347]
I renamed the library tmpuitest2 to tmpuitest3, but we can see the iproj.json and the library list did not reflect this change.

https://github.com/IBM/vscode-ibmi-projectexplorer/assets/42983653/fdff8126-afe3-43fa-8f92-9dd4332ae3f7

**Comment by jonnyz32** [comment]
Found in libraryListTest

**Comment by edmundreinhardt** [comment]
LIkewise @SanjulaGanepola understands this limitation and plans to address it
