### ISSUE TITLE
Deleting a library in library list doesn't remove the library from the library list

### ISSUE THREAD

**Issue by jonnyz32** [IBM/vscode-ibmi-projectexplorer#348]
https://github.com/IBM/vscode-ibmi-projectexplorer/assets/42983653/9a2e1047-bd9e-4f5f-a496-9f169eb80da5

**Comment by edmundreinhardt** [comment]
@SanjulaGanepola Sanjula confirms that there is missing functionality to update the iproj.json when deleting or renaming a library.  The view reflects iproj.json and therefore still shows the old library
