### ISSUE TITLE
Create Source File not working

### ISSUE THREAD

**Issue by jonnyz32** [IBM/vscode-ibmi-projectexplorer#349]
After creating the source file, I can't see it in the library list nor object browser

https://github.com/IBM/vscode-ibmi-projectexplorer/assets/42983653/57fc7e1a-309c-48cd-bf0a-98b0fb9a8fb0

**Comment by edmundreinhardt** [comment]
Can I assume this is with WDSCTEST on P8adt05

**Comment by jonnyz32** [comment]
It was yes. It's working better today, admittedly

**Comment by edmundreinhardt** [comment]
so it doesn't reproduce consistently :-(

**Comment by jonnyz32** [comment]
I know Rob mentioned that this machine was undergoing maintenance, so that could be one factor. It may be that our error handling, does not handle this case properly.

**Comment by edmundreinhardt** [comment]
So if I create a SRC-PF and then expand the library it shows.  I suspect that this is also a refresh issue
