### ISSUE TITLE
Change library description not working

### ISSUE THREAD

**Issue by jonnyz32** [IBM/vscode-ibmi-projectexplorer#350]
In the below recording, you can see I changed the library description but it is not reflected in the project explorer

https://github.com/IBM/vscode-ibmi-projectexplorer/assets/42983653/43627e7e-a91c-46de-9414-b58c8ce9217b

**Comment by edmundreinhardt** [comment]
Reproduced the problem in VS Code
The implementation is a very thin wrapper around call to Code4i

```
      commands.registerCommand(`vscode-ibmi-projectexplorer.changeObjectDescription`, async (element: ObjectFile) => {
        if (element) {
          await commands.executeCommand(`code-for-ibmi.changeObjectDesc`, toObjectBrowserObject(element));
          this.refresh();
        }
      }),
```
https://gitkraken.dev/link/dnNjb2RlOi8vZWFtb2Rpby5naXRsZW5zL2xpbmsvci8xYmY0NmQwZmI4YzgzNWZmNDIxMzJmYWE1ZWY3MWZmYTZmZWFkM2UyL2Yvc3JjL3ZpZXdzL3Byb2plY3RFeHBsb3Jlci9pbmRleC50cz91cmw9aHR0cHMlM0ElMkYlMkZnaXRodWIuY29tJTJGSUJNJTJGdnNjb2RlLWlibWktcHJvamVjdGV4cGxvcmVyLmdpdCZsaW5lcz05Mjc%3D?origin=gitlens

**Comment by edmundreinhardt** [comment]
```
function toObjectBrowserObject(objectFile: Library | ObjectFile) {
  const object = Object.assign({}, "objectFileInfo" in objectFile ? objectFile.objectFileInfo : objectFile.libraryInfo);
  return {
    path: `${object.library}/${object.name}`,
    object,
    updateDescription: () => { }
  };
}
```

**Comment by edmundreinhardt** [comment]
It turns out that the  setting of the description is successful but the Project Explorer does not reflect it

**Comment by jonnyz32** [comment]
Validated on my end
