### ISSUE TITLE
Create Source Member, not showing new member in project explorer

### ISSUE THREAD

**Issue by jonnyz32** [IBM/vscode-ibmi-projectexplorer#356]
Check screen recording in box under: IBM i Merlin/Screencaps/Create Source Member Not Working.mov

**Comment by jonnyz32** [comment]
I'm also getting this error notification 
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/42983653/c36673a9-e169-45c7-9530-b4294b654439)

**Comment by edmundreinhardt** [comment]
@SanjulaGanepola I sent you screen cap
