### ISSUE TITLE
Copy Object not showing new object in project explorer

### ISSUE THREAD

**Issue by jonnyz32** [IBM/vscode-ibmi-projectexplorer#357]
See recording in Box: IBM i Merlin/Screencaps/Copy Object Not Working.mov

**Comment by jonnyz32** [comment]
It seems after refreshing the workspace this is working

**Comment by edmundreinhardt** [comment]
@SanjulaGanepola I can reproduce this.  I will send you the screen recording

**Comment by edmundreinhardt** [comment]
@jonnyz32 I can't reproduce on either environment.
