### ISSUE TITLE
Build Current Action for ibmi-bob failing

### ISSUE THREAD

**Issue by irfanshar** [IBM/vscode-ibmi-projectexplorer#360]
Build Current Action for ibmi-bob failing.
I believe the error may have to do with the &BASENAME defined in the command for Build current in the actions.json.
```"command": "OPT=*EVENTF BUILDLIB=&CURLIB /QOpenSys/pkgs/bin/makei compile -f &BASENAME",```

https://github.com/IBM/vscode-ibmi-projectexplorer/assets/59372176/33b82db6-b1fd-45e3-bc23-a0f7af08b199

**Comment by edmundreinhardt** [comment]
Hmm this is Code 4 i functionality.  We should
(if you do Ctrl-Shift-B or the crossed tools icon on the Project Explorer heading, you will be prompted with the correct BOB  build command.)
I will investigate if the default for Code 4 i is broken and open an issue there.

**Comment by worksofliam** [comment]
@irfanshar 

Looks like the issue you're seeing is here:

```
      commands.registerCommand(`vscode-ibmi-projectexplorer.runAction`, async (element: Project | ObjectFile | MemberFile) => {
        if (element) {
          if (element instanceof Project) {
            await ProjectManager.setActiveProject(element.workspaceFolder);

            await commands.executeCommand(`code-for-ibmi.runAction`, {
              resourceUri: element.workspaceFolder.uri
            });
          }
```

When you're running an Action and using `&BASENAME`, it's pulling the base name from the URI you're in. Perhaps what should be done here, instead of passing the workspace folder URI is that you should pass in the active editor perhaps - if it's in the current project.

**Comment by worksofliam** [comment]
@irfanshar 

Maybe something like this?

```ts
            await ProjectManager.setActiveProject(element.workspaceFolder);

            const activeProject = ProjectManager.getActiveProject();
            let chosenUri = activeProject?.workspaceFolder.uri;
            let activeEditor = window.activeTextEditor;

            if (activeEditor) {
              const editorProject = ProjectManager.getProjectFromUri(activeEditor.document.uri);
              if (activeProject?.getName() === editorProject?.getName()) {
                chosenUri = activeEditor.document.uri;
              }
            }

            await commands.executeCommand(`code-for-ibmi.runAction`, {
              resourceUri: chosenUri
            });
```
