### ISSUE TITLE
Create a walkthrough to set up an i project

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/vscode-ibmi-projectexplorer#37]
1) From scratch
- add workspace folder
- create iproj.json (via clicking on project tree item)
- connect to IBM i (right click action to do Merlin/Code for IBM i connection creation/selection)
- create .env ( click on Variables entry)
- assign library to a variable (need new action)
- tweak/reorder library list
- set deploy location

3) from QSYS library
- do import using ...

**Comment by SanjulaGanepola** [comment]
Closing as walkthroughs have been added
