### ISSUE TITLE
e.toUpperCase is not a function when expanding source files from /QSYS.LIB/AURORABRA

### ISSUE THREAD

**Issue by jonnyz32** [IBM/vscode-ibmi-projectexplorer#379]
https://github.com/IBM/vscode-ibmi-projectexplorer/assets/42983653/0214836a-3847-4701-86d6-0997f84418c9

**Comment by edmundreinhardt** [comment]
confirmed with Jonathan that this   is fixed with the latest 2.8.0 version of Code 4 i
