### ISSUE TITLE
Remove Upload And Replace Member Action 

### ISSUE THREAD

**Issue by irfanshar** [IBM/vscode-ibmi-projectexplorer#396]
<img width="1728" alt="image" src="https://github.com/IBM/vscode-ibmi-projectexplorer/assets/59372176/e3ef7765-8a24-4ef0-9645-e5d6954ac0a1">

**Comment by edmundreinhardt** [comment]
THe command is shown because of
    {
          "command": "vscode-ibmi-projectexplorer.uploadAndReplace",
          "when": "view == projectExplorer && viewItem =~ /^member*/",
          "group": "5_transfer@1"
        },
        
in package.json
Not sure if I can make the "when" clause sensitive to whether we are in Merlin
@irfanshar Did we always want to remove this or only if we are in Merlin?

**Comment by SanjulaGanepola** [comment]
> Not sure if I can make the "when" clause sensitive to whether we are in Merlin

@edmundreinhardt FYI, this is possible in fact by setting a custom context value when the extension is started. If this is needed, let me know and I can add the logic for this.

**Comment by edmundreinhardt** [comment]
@SanjulaGanepola that would be very helpful.  The current action prompts for files from the Merlin container rather that workstation and so is not useful in Merlin
