### ISSUE TITLE
Actions CRTSRVPGM and CRTPGM not successful

### ISSUE THREAD

**Issue by irfanshar** [IBM/vscode-ibmi-projectexplorer#397]
https://github.com/IBM/vscode-ibmi-projectexplorer/assets/59372176/cbc4d226-3df8-42f0-9751-65c1e3bc5742

**Comment by sebjulliand** [comment]
Why running these commands on a BNDDIR though?

**Comment by edmundreinhardt** [comment]
I agree Seb, the Create Program should not be run against CL pseudo source.
So the question is why runAction menu gives those options.  Is this a limitation of Code 4 i
In any case, the buildCurrent action of the iProj should be chosen, as runAction is not designed with iproj.json projects

**Comment by sebjulliand** [comment]
Actions can be restricted to some extensions:
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11096890/5ea977d0-6709-4b23-aa40-deb4bbc5ab01)

So I assume that the actions defined in @irfanshar's workspace do not have this field filled in.

**Comment by edmundreinhardt** [comment]
I opened this issue on Code 4 i as it is not a Project Explorer issue.
https://github.com/IBM/vscode-ibmi-projectexplorer/assets/59372176/cbc4d226-3df8-42f0-9751-65c1e3bc5742

The default actions setup creates actions with GLOBAL applicability.
