### ISSUE TITLE
Keep Code 4 IBM i LIBL and CURLIB in synch with the Project Explorer LIBL

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/vscode-ibmi-projectexplorer#421]
Today when an Code for IBM i action, it uses the Code for IBM i library list which is not the same as the one defined by the iproj.json from the project.
Hence when the `Run Action` is executed from the project
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/6c37b9a7-2cfd-403d-9a2c-555bc88fb4b5)

or active editor
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/24286a29-b106-4097-aac4-b1b76d75c46f)

the wrong library is used as CURLIB or to look up DB Refs or includes

**Comment by edmundreinhardt** [comment]
The solution is to maintain the `.env` variables CURLIB and LIBL whenever iproj.json `curlib` and `preUsrlibl` and `postUsrlibl` and reference variables change.

@SanjulaGanepola Sanjula could you tackle this?

**Comment by sebjulliand** [comment]
A few points to consider before doing this:
- We'll need new commands in `Code for i` to do this. Changing current library is already possible, changing the entire library list is not.
- Project Explorer should not change the default library list but instead create a dedicated `profile` (always the same; so, create it if needed), make it active and change its library list. This may require new commands too (to be checked).
This way, the users won't loose their default library list when using Project Explorer.

**Comment by SanjulaGanepola** [comment]
@edmundreinhardt I will be a bit busy for the next two weeks, so I likely won't be able to get a fix in until then. And as Sebastien mentioned, this will require changes in `Code for i`

**Comment by worksofliam** [comment]
I mentioned this to Edmund, I don't believe changing Code for IBM i is the right way to do this. I think, per project, should be using the `.env` file, which would be automatically updated when the project library list changes.

**Comment by edmundreinhardt** [comment]
Note that this is a duplicate of #254

**Comment by edmundreinhardt** [comment]
@worksofliam @sebjulliand 
It is not clear from Seb's comments whether it is sufficient to update the `LIBL` variable in .env in order to affect the library list used when running Code for IBM i actions.  Could you please clarify?
