### ISSUE TITLE
Download member action fails with "Cannot read properties of undefined"

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/vscode-ibmi-projectexplorer#422]
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/a0e5ee48-e819-471e-b425-85e69f6ab92e)
The above error appears when doing the action `Download` on an IBM i member
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/81fd2f51-6c9b-4b5c-9e3b-78c46b6fd47c)

My guess is that the memberFileInfo for the MemberFile TreeItem is undefined and the error is caused when getting the 'name' attribute
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/1f0f396f-2068-473a-81bb-6f865fb2b7aa)

**Comment by edmundreinhardt** [comment]
@SanjulaGanepola Could you look at this, I am having difficulty debugging it.

**Comment by sebjulliand** [comment]
@edmundreinhardt I see the problem, I'll fix that for you.

**Comment by sebjulliand** [comment]
The problem was due to a change in the download command that expected a specific class and it's subtypes instead of the interfaces used previously. I changed that back in this PR https://github.com/codefori/vscode-ibmi/pull/1960 and it fixes the issue.
