### ISSUE TITLE
vscode-ibmi `getObjectList` API change

### ISSUE THREAD

**Issue by worksofliam** [IBM/vscode-ibmi-projectexplorer#449]
As of Code for IBM i 2.10.1, the result of `getObjectList` with `*SRCPF` no longer returns `ccsid` or `memberCount`.

I don't know if these are used by Project Explorer, but thought it'd be worth an issue to investigate.

**Comment by worksofliam** [comment]
Had a quick look at the code. I believe there is no impact to PE.

**Comment by edmundreinhardt** [comment]
So do we need change our call to that API?
@worksofliam

**Comment by worksofliam** [comment]
@edmundreinhardt No, we just removed two props from the result.
