### ISSUE TITLE
Add action toggle on Problems view to set preference to keep only the last build/compile problems

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/vscode-ibmi-projectexplorer#473]
https://github.ibm.com/ibmi-toronto/cloudide4i/issues/2100

**Comment by edmundreinhardt** [comment]
Optionally add another action to clear previous problems, clears contents of .evfevent directory

**Comment by SanjulaGanepola** [comment]
@edmundreinhardt We merged in the toggle action so that we can create a release. I created a new issue to tracking adding those optional actions

**Comment by edmundreinhardt** [comment]
Merge in the walkthroughs while you are at it
