### ISSUE TITLE
Commands from other extensions are accidently being added to tree items

### ISSUE THREAD

**Issue by SanjulaGanepola** [IBM/vscode-ibmi-projectexplorer#524]
From source orbit:
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/32170854/d04f67c4-5bfb-4c71-8685-e268304ee59b)

From Db2i:
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/32170854/41efdd42-34dc-4c26-9b1c-fe74fe30149f)

**Comment by SanjulaGanepola** [comment]
@edmundreinhardt Should we add an actual `Go to file` action like in the first picture?

**Comment by SanjulaGanepola** [comment]
SO Fix -> https://github.com/IBM/sourceorbit/pull/71

**Comment by AIforIBMi** [comment]
The compiled object may or may not exist - depending if the build was successful.  But given sufficient guards, I can this as being useful.  Where would the file be shown?  In the Code 4 i Object Browser?  Under what filter?

**Comment by AIforIBMi** [comment]
Would be nice if we could show in in the Project Explorer view where we have the objib already filtered.
