### ISSUE TITLE
IBMi-bob file names problem

### ISSUE THREAD

**Issue by cosentino-smeup** [IBM/vscode-ibmi-projectexplorer#571]
Hello, I have used SourceOrbit to generate the "Rules.mk" files. It looks like the are problems with objects names that start with "$" 

```
$LOWKXT0F.FILE: $LOWKXT0F.PF
$LOWKXT0L.FILE: $LOWKXT0L.LF $LOWKXT0F.FILE

```

![rules](https://github.com/user-attachments/assets/1846345b-8fdf-4d71-ac2a-96d994026a57)

Is there a way to make SourceOrbit to accept these characters?

**Comment by SanjulaGanepola** [comment]
@cosentino-smeup Thanks for posting this issue. I see that you also opened it in the Source Orbit repo [here](https://github.com/IBM/sourceorbit/issues/78) which would be the best place to discuss this particular issue. Shall I close this issue in favor of having the discussion there?

**Comment by cosentino-smeup** [comment]
> @cosentino-smeup Thanks for posting this issue. I see that you also opened it in the Source Orbit repo [here](https://github.com/IBM/sourceorbit/issues/78) which would be the best place to discuss this particular issue. Shall I close this issue in favor of having the discussion there?

Yes please close it. I realized after that I should have opened it in a different place.

Thank you
