### ISSUE TITLE
IBMi-bob - Deploy and build errors with Project Explorer 

### ISSUE THREAD

**Issue by cosentino-smeup** [IBM/vscode-ibmi-projectexplorer#576]
When I execute the build of a project with IBMi-bob I get this error (build.log):

`bsh:` LIBL=IBMBOB_C QTEMP SMEUP_DAT SMETAB PER_SRVL SMEDEV QGPL: is not an identifier

If I repeat the build, I get this error (build-2.log):

```
Starting MD5 synchronization transfer
Deployment failed: TypeError: Cannot read properties of undefined (reading 'trim')
```

If I tried cleaning the IFS folder but it doesn't change.
I also created the following files in my home directory: .profile and .bashrc

I did the same thins on another IBMi and there weren't any issues. 

What could be the problem?

[build.log](https://github.com/user-attachments/files/16864028/build.log)
[build-2.log](https://github.com/user-attachments/files/16864042/build-2.log)

**Comment by SanjulaGanepola** [comment]
Hello @cosentino-smeup. Can you share the content of your `iproj.json` and `.env` file? If you prefer to send it privately, please email Sanjula.Ganepola@ibm.com

Also, can you please share the full Code for IBM i log after reproducing the error. This can be downloaded from the `Help View`:

![image](https://github.com/user-attachments/assets/83c20584-3591-4df3-8777-bc530914f52d)

**Comment by cosentino-smeup** [comment]
Hello @SanjulaGanepola I have just shared a folder on google drive with you containing the things you required.

I used the [IBM example repository](https://github.com/IBM/bob-recursive-example) to reproduce the error. 

Thank you

**Comment by SanjulaGanepola** [comment]
Thanks for sharing that. Looks like your `$SHELL` is not set to `bash`. You should see the following notification when this happens:

![image](https://github.com/user-attachments/assets/74250dbe-4719-4e8f-aff5-23e565090fa4)

After you do this, reconnect and try building.

**Comment by cosentino-smeup** [comment]
> Thanks for sharing that. Looks like your `$SHELL` is not set to `bash`. You should see the following notification when this happens:
> 
> ![image](https://private-user-images.githubusercontent.com/32170854/364803496-74250dbe-4719-4e8f-aff5-23e565090fa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDQ1ODksIm5iZiI6MTcyNTU0NDI4OSwicGF0aCI6Ii8zMjE3MDg1NC8zNjQ4MDM0OTYtNzQyNTBkYmUtNDcxOS00ZThmLWFmZjUtMjNlNTY1MDkwZmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDEzNTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMWM3OTRmYzllNWNiMzg2ZDA4MjIzN2VhZGNiMDI4Y2U0YTQwZDgwMTAxMTZkNzQ2ZjM1ZTUyNTc2NTQwOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.79Ytp4i2oR-yfDMxQVqAFDM4AFBpE70ArqdbDfINgS4)
> 
> After you do this, reconnect and try building.

That's it !!! now it works .. thank you!
