### ISSUE TITLE
Code for IBMi - encoding

### ISSUE THREAD

**Issue by cosentino-smeup** [IBM/vscode-ibmi-projectexplorer#588]
I am using the 5250 terminal from "Code for IBMi" and I have set the encoding to "280" (Italy) but some characters are wrong.
For Example, "£UI_SRC" is shown with a different initial character. "£" is not being converted correctly. (See the attachment).

![wrong char](https://github.com/user-attachments/assets/4c1ba576-fe1b-4aba-8820-a85330806e63)

**Comment by SanjulaGanepola** [comment]
Looks like this could be an issue with `tn5250` itself as I am also noticing similar behavior. Could you open an issue in that project's repository: https://github.com/tn5250/tn5250

@worksofliam Have you seen this issue before?

**Comment by worksofliam** [comment]
@SanjulaGanepola Yes. We just got this same issue and suggested they open an issue on tn5250 also.

**Comment by cosentino-smeup** [comment]
@SanjulaGanepola, done.

**Comment by cosentino-smeup** [comment]
> Looks like this could be an issue with `tn5250` itself as I am also noticing similar behavior. Could you open an issue in that project's repository: https://github.com/tn5250/tn5250
> 
> @worksofliam Have you seen this issue before?

@SanjulaGanepola, done.
