### ISSUE TITLE
Support iASP

### ISSUE THREAD

**Issue by worksofliam** [IBM/vscode-ibmi-projectexplorer#6]

**Comment by SanjulaGanepola** [comment]
Closing as `iASP` is being removed from iproj.json

**Comment by edmundreinhardt** [comment]
OK, but does Project Explorer work with iASPs?
Has this  been validated?

**Comment by SanjulaGanepola** [comment]
I have not yet tested this scenario. Will reopen this issue.

**Comment by edmundreinhardt** [comment]
Tested and validated
