### ISSUE TITLE
Deleting a library doesn't clear it from library list

### ISSUE THREAD

**Issue by ThePrez** [IBM/vscode-ibmi-projectexplorer#608]
Steps to recreate:

1. Create a library `rascal` (choose any name)

2. Add library `rascal` to library list
3. Right-click on the library and go to "Delete Library"
4. Observe that the library still exists in the `iproj.json` file
```json
{
  "description": "migration demo",
  "preUsrlibl": [
    "rascal"
  ]
}
```

**Comment by SanjulaGanepola** [comment]
@ThePrez I can't seem to be able to reproduce this issue. Looking at our code, it looks like we already handle removing it from `iproj.json` (if hardcoded or added as a variable) if you do it from PE. Did you use `Delete Library` from PE or Code4i's Object Browser? If from the Object Browser, this is a Code4i action which will not do anything to `iproj.json`. In this case, the user would have to manually remove it.

**Comment by ThePrez** [comment]
I am able to reliably by using "Delete Library" from PE. How can I gather useful data?

**Comment by SanjulaGanepola** [comment]
Ending up finding the problem. Simple casing issue.
