### ISSUE TITLE
Suggestion for more explicit confirmation of library delete

### ISSUE THREAD

**Issue by ThePrez** [IBM/vscode-ibmi-projectexplorer#609]
The confirmation dialog when deleting a library is phrased like so:
```rpc
Are you sure you want to delete QSYS/RASCAL *LIB?
```

As a first-time user of this extension, and given that I was taking an action from the "library list" view, I thought it was just deleting the library from the library list, not _actually_ deleting the library from disk (I missed the context clues from the adjacent options like "clear library" and "copy"). Thankfully I was supervised by a helpful @edmundreinhardt 

I may be the "odd one out" in thinking that the delete action actually deleted the library, so feel free to close this without changes if yous see fit. 

One proposal, however, would be to make the warning/confirmation more explicit, for instance:
```rpc
This option will delete library RASCAL (and all of its contents) from the IBM i system. Are you sure you want to do this?
```

**Comment by mipjones** [comment]
You are definitely not the "odd one out", I concur your sentiment. Great confirmation message proposal. It would be even safer if we add: 
`This action cannot be undone.`
